---
    - debug:
        var: all_vols

    #- name: make output dir
    #  file:
    #    path: "{{ zvmguests_output }}"
    #    state: directory
#
    - name: "creating svc vol -- {{ item }}"
      include_tasks: svc_operations.yml
      with_items: "{{ all_vols }}"


    