---
- name: Create a volume
  ibm.spectrum_virtualize.ibm_svc_manage_volume:
    clustername: "{{ clustername }}"
    domain: "{{domain}}"
    username: "{{ username }}"
    password: "{{ password }}"
    log_path: /tmp/playbook.debug
    name: "{{item.hostname}}{{ item.volname_prefix }}{{ (100000 | random | to_uuid | lower)[:8] }}"
    state: "present"
    pool: "NLSAS_Tier2_pool"
    size: "{{item.vol_size}}"
    unit: "{{item.vol_unit}}"
    iogrp: "io_grp0,io_grp1,io_grp2,io_grp3"
    #volumegroup: "test_volumegroup"

#- name: Delete a host
#  ibm.spectrum_virtualize.ibm_svc_host:
#    clustername: "{{clustername}}"
##    domain: "{{domain}}"
#    username: "{{username}}"
#    password: "{{password}}"
#    log_path: /tmp/playbook.debug
#    name: "{{item}}"
#    state: absent
- name: scsi-rescan
  delegate_to: "{{item.hostname}}"
  shell: scsi-rescan --luns lun1,lun2
  register: rescan_output




#- name: Run svcinfo CLI command using SSH client with password
#  ibm.spectrum_virtualize.ibm_svctask_command:
#    command: "svctask rmhost {{item}}"
#    clustername: "{{clustername}}"
#    username: "{{username}}"
#    password: "{{password}}"
#    log_path: /tmp/playbook.debug
#  register: svctask_cmd_output

