---
#- name: Create a volume
#  ibm.spectrum_virtualize.ibm_svc_manage_volume:
#    clustername: "{{ clustername }}"
#    domain: "{{domain}}"
#    username: "{{ username }}"
##    password: "{{ password }}"
#    log_path: /tmp/playbook.debug
#    name: "{{item.hostname}}_{{ item.volname_prefix }}_{{ (100000 | random | to_uuid | lower)[:8] }}"
#    state: "present"
#    pool: "{{item.pool_name}}"
#    size: "{{item.vol_size}}"
##    unit: "{{item.vol_unit}}"
#    iogrp: "{{item.io_grps}}"
    #volumegroup: "test_volumegroup"

- name: Run svcinfo CLI command using SSH client with password
  ibm.spectrum_virtualize.ibm_svcinfo_command:
    command: "svcinfo lsvdisk -delim : RHEL8401osf4b823d6"
    clustername: "{{clustername}}"
    username: "{{username}}"
    password: "{{password}}"
    log_path: /tmp/playbook.debug
  register: svcinfo_cmd_output

- name: get the volume wwid tmp
  set_fact:
     vol_wwid_tmp: "{{svcinfo_cmd_output.stdout}}"

- name: get the volume wwid
  delegate_to: "{{item.hostname}}"
  shell: echo {{vol_wwid_tmp[0]}} | cut -d ',' -f1 | grep vdisk_UID 
  register: rescan_output

- name: get the volume wwid
  set_fact:
     vol_wwid: "{{rescan_output}} "

- debug: var=vol_wwid
#- name: Delete a host
#  ibm.spectrum_virtualize.ibm_svc_host:
#    clustername: "{{clustername}}"
##    domain: "{{domain}}"
#    username: "{{username}}"
#    password: "{{password}}"
#    log_path: /tmp/playbook.debug
#    name: "{{item}}"
#    state: absent
- name: scsi-rescan
  delegate_to: "{{item.hostname}}"
  shell: scsi-rescan --luns lun1,lun2
  register: rescan_output




#- name: Run svcinfo CLI command using SSH client with password
#  ibm.spectrum_virtualize.ibm_svctask_command:
#    command: "svctask rmhost {{item}}"
#    clustername: "{{clustername}}"
#    username: "{{username}}"
#    password: "{{password}}"
#    log_path: /tmp/playbook.debug
#  register: svctask_cmd_output

