---
# Sample module-level playbook of the IBM Z HMC Collection
    #- name: Read CSV
    #  read_csv:
    #        path:  /tmp/zvmguests.csv
    #  register: zvmguests_template
    - debug:
        var: zvms_template

    #- name: make output dir
    #  file:
    #    path: "{{ zvmguests_output }}"
    #    state: directory
#
    - name: "Working on -- {{ item.zvmname }}"
      include_tasks: zvm_operations.yml
      with_items: "{{ zvms_template.list }}"


    

