---
- name: Get the WWPN info  
  delegate_to: "{{target_vm}}"
  tags: vm-cfg
  shell: vmcp q v fcp | grep WWPN | head -n1 | sed -e 's/.*WWPN\(.*\)/\1/' | tr -d ' \t\n\r'
  register: cmd_output
- name: Set the target WWPN
  set_fact: 
     vm_fcp_wwpn: "{{ cmd_output.stdout }}"

- name: Get the zVM username
  delegate_to: "{{target_vm}}"
  tags: vm-cfg
  shell: cat /proc/sysinfo | grep 'VM00 Name:' | cut -d ':' -f2 | tr -d ' \t\n\r'
  register: cmd_output

- name: Set the target vm username
  set_fact: 
     vm_name: "{{ cmd_output.stdout }}"



- name: Define a new FC host
  ibm.spectrum_virtualize.ibm_svc_host:
    clustername: "{{clustername}}"
    #domain: "{{domain}}"
    username: "{{username}}"
    password: "{{password}}"
    log_path: /tmp/playbook.debug
    name: "{{vm_name}}"
    state: present
    fcwwpn: "{{vm_fcp_wwpn}}"
    iogrp: 0:1:2:3
    protocol: scsi
    type: generic
    #site: site-name

- name: Run svcinfo CLI command using SSH client with password
  ibm.spectrum_virtualize.ibm_svcinfo_command:
    command: "svcinfo lshost {{vm_name}}"
    clustername: "{{clustername}}"
    username: "{{username}}"
    password: "{{password}}"
    log_path: /tmp/playbook.debug
  register: svcinfo_cmd_output


  #until: svcinfo_cmd_output.stdout.find("consistent_synchronized") != -1
  #retries: 3000
  #delay: 3


