---
# Sample module-level playbook of the IBM Z HMC Collection
    #- name: Read CSV
    #  read_csv:
    #        path:  /tmp/zvmguests.csv
    #  register: zvmguests_template
    - debug:
        var: zvmguests_template

    #- name: make output dir
    #  file:
    #    path: "{{ zvmguests_output }}"
    #    state: directory
#
    - name: "Creating user direct files -- {{ item.zvm_uname }}"
      include_tasks: zvm_operations.yml
      with_items: "{{ zvmguests_template.list }}"


    

