---
- name: Get the current zVM CPU info
  tags: zvm-cfg
  shell: vmcp query processor
  register: cmd_output

- name: Get the current zVM Mem info
  tags: zvm-cfg
  shell: vmcp query stor
  register: cmd_output

- name: Get the current zVM Mem size
  tags: zvm-cfg
  shell: vmcp query stor | grep 'Reconfigurable =' | sed -e 's/.*Reconfigurable =\(.*\)Maximum.*/\1/' | tr -d ' \t\n\r' | cut -d 'G' -f1
  register: cmd_output

- name: Set the target memory size
  set_fact: 
     zvm_stor_size: "{{ cmd_output.stdout |int - item.mem_size |int }}"

- name: generate cpu offline script
  tags: cpu-cfg
  #become: yes
  #become_user: root
  template:
    src: vary_off_zvm.sh.j2
    dest: "/tmp/vary_off_zvm.sh"
    mode: a+x
  when: 
    - queryonly == false

- name: generate cpu online script
  tags: cpu-cfg
  #become: yes
  #become_user: root
  template:
    src: vary_on_zvm.sh.j2
    dest: "/tmp/vary_on_zvm.sh"
    mode: a+x
  when: 
    - queryonly == false

- name: Offline the CPU 
  tags: cpu-cfg
  shell: /tmp/vary_off_zvm.sh {{item.cpu_num}} doit
  register: cmd_output
  when: 
    - queryonly == false
    - item.cpu_inc == false

- name: Online the CPU 
  tags: cpu-cfg
  shell: /tmp/vary_on_zvm.sh {{item.cpu_num}} doit
  register: cmd_output
  when: 
    - queryonly == false
    - item.cpu_inc == true

- name: Reduce the Memory size
  tags: mem-cfg
  shell: "vmcp set stor RECONFigurable {{zvm_stor_size}}G"
  register: cmd_output
  when: 
    - queryonly == false
    - item.mem_inc == false
    - zvm_stor_size > 0

- name: Reduce the Memory size
  tags: mem-cfg
  shell: "vmcp set stor RECONFigurable {{zvm_stor_size}}"
  register: cmd_output
  when: 
    - queryonly == false
    - item.mem_inc == false
    - zvm_stor_size == 0

- name: Increase the Memory size
  tags: mem-cfg
  shell: "vmcp set stor RECONFigurable +{{item.mem_size}}G"
  register: cmd_output
  when: 
    - queryonly == false
    - item.mem_inc == true

- name: Get the current zVM CPU info
  tags: zvm-cfg
  shell: vmcp query processor
  register: cmd_output
  when: 
    - queryonly == false

- name: Get the current zVM Mem info
  tags: zvm-cfg
  shell: vmcp query stor
  register: cmd_output
  when: 
    - queryonly == false


#- name: Changing CPU number
#  tags: zvm-cfg
#  shell: cp "{{ zvmguests_output_rhel79 }}/{{item.zvm_uname|upper}}.PRM" /mnt/rhel79/
##  register: cmd_output
#  when: item.profile == "INST79"
#- debug: var=cmd_output
