---
- name: Get the current zVM CPU info
  tags: zvm-cfg
  shell: vmcp query processor
  register: cmd_output

- debug: var=cmd_output

- name: Get the current zVM Mem info
  tags: zvm-cfg
  shell: vmcp query stor
  register: cmd_output

- debug: var=cmd_output

#- name: Changing CPU number
#  tags: zvm-cfg
#  shell: cp "{{ zvmguests_output_rhel79 }}/{{item.zvm_uname|upper}}.PRM" /mnt/rhel79/
##  register: cmd_output
#  when: item.profile == "INST79"
#- debug: var=cmd_output
