---
- name: Get the current zVM CPU info
  tags: zvm-cfg
  shell: vmcp query processor
  register: cmd_output

- debug: var=cmd_output.stdout

- name: Get the current zVM Mem info
  tags: zvm-cfg
  shell: vmcp query stor
  register: cmd_output

- debug: var=cmd_output.stdout

- name: Change the CPU number
  tags: cpu-cfg
  shell: echo test
  register: cmd_output

- name: Reduce the Memory size
  tags: mem-cfg
  shell: "vmcp set stor RECONFigurable -{{item.mem_size}}"
  when: 
    - queryonly == false
    - item.mem_inc == false

- name: Increase the Memory size
  tags: mem-cfg
  shell: "vmcp set stor RECONFigurable +{{item.mem_size}}"
  when: 
    - queryonly == false
    - item.mem_inc == true

- name: Get the current zVM CPU info
  tags: zvm-cfg
  shell: vmcp query processor
  register: cmd_output
  when: 
    - queryonly == false

- debug: var=cmd_output.stdout
  when: 
    - queryonly == false

- name: Get the current zVM Mem info
  tags: zvm-cfg
  shell: vmcp query stor
  register: cmd_output
  when: 
    - queryonly == false

- debug: var=cmd_output.stdout
  when: 
    - queryonly == false

#- name: Changing CPU number
#  tags: zvm-cfg
#  shell: cp "{{ zvmguests_output_rhel79 }}/{{item.zvm_uname|upper}}.PRM" /mnt/rhel79/
##  register: cmd_output
#  when: item.profile == "INST79"
#- debug: var=cmd_output
