
- name: Create component list
  set_fact:
    all_vols: "{{ all_vols | default([]) + [vols_list[index1|int]] }}"
  with_sequence: start=1 end={{ vols_list[index1|int].vol_num }}

- name: Reset the index
  set_fact:
    index1: "{{ index1 | int + 1 }}"

#- name: Print the result
#  debug:
#    var: all_sg_vols  
